version: "3.3"
services:
  nest:
    image: node:20
    restart: "always"
    volumes:
      - ./:/nest-agro/
    ports:
      - 9999:8000
    working_dir: /nest-agro/
    command: npm install 
    entrypoint: npm run start